/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ButtonControl extends ControlObject {
  private long swigCPtr;

  protected ButtonControl(long cPtr, boolean cMemoryOwn) {
    super(openpadJNI.ButtonControl_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ButtonControl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        openpadJNI.delete_ButtonControl(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ButtonControl(float x, float y, float w, int controlid, int btntype) {
    this(openpadJNI.new_ButtonControl(x, y, w, controlid, btntype), true);
  }

  public SWIGTYPE_p_Value serializeJSON(SWIGTYPE_p_Document__AllocatorType a) {
    return new SWIGTYPE_p_Value(openpadJNI.ButtonControl_serializeJSON(swigCPtr, this, SWIGTYPE_p_Document__AllocatorType.getCPtr(a)), false);
  }

  public void setBtntype(int value) {
    openpadJNI.ButtonControl_btntype_set(swigCPtr, this, value);
  }

  public int getBtntype() {
    return openpadJNI.ButtonControl_btntype_get(swigCPtr, this);
  }

}
