/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.openpad.server;

public class Client {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Client(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Client obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        openpadJNI.delete_Client(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSocketID(int value) {
    openpadJNI.Client_socketID_set(swigCPtr, this, value);
  }

  public int getSocketID() {
    return openpadJNI.Client_socketID_get(swigCPtr, this);
  }

  public void setSock(SWIGTYPE_p_TCPSocket value) {
    openpadJNI.Client_sock_set(swigCPtr, this, SWIGTYPE_p_TCPSocket.getCPtr(value));
  }

  public SWIGTYPE_p_TCPSocket getSock() {
    long cPtr = openpadJNI.Client_sock_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_TCPSocket(cPtr, false);
  }

  public void setServ(Server value) {
    openpadJNI.Client_serv_set(swigCPtr, this, Server.getCPtr(value), value);
  }

  public Server getServ() {
    long cPtr = openpadJNI.Client_serv_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Server(cPtr, false);
  }

  public void setUserData(SWIGTYPE_p_void value) {
    openpadJNI.Client_userData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUserData() {
    long cPtr = openpadJNI.Client_userData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setShouldRun(boolean value) {
    openpadJNI.Client_shouldRun_set(swigCPtr, this, value);
  }

  public boolean getShouldRun() {
    return openpadJNI.Client_shouldRun_get(swigCPtr, this);
  }

  public void setHasJoined(boolean value) {
    openpadJNI.Client_hasJoined_set(swigCPtr, this, value);
  }

  public boolean getHasJoined() {
    return openpadJNI.Client_hasJoined_get(swigCPtr, this);
  }

  public void setClientID(SWIGTYPE_p_shared_ptrT_openpad__IDObject_t value) {
    openpadJNI.Client_clientID_set(swigCPtr, this, SWIGTYPE_p_shared_ptrT_openpad__IDObject_t.getCPtr(value));
  }

  public SWIGTYPE_p_shared_ptrT_openpad__IDObject_t getClientID() {
    long cPtr = openpadJNI.Client_clientID_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_shared_ptrT_openpad__IDObject_t(cPtr, false);
  }

  public Client(SWIGTYPE_p_TCPSocket sock, int sockID, Server serv) {
    this(openpadJNI.new_Client(SWIGTYPE_p_TCPSocket.getCPtr(sock), sockID, Server.getCPtr(serv), serv), true);
  }

  public void send(Serializable s) {
    openpadJNI.Client_send(swigCPtr, this, Serializable.getCPtr(s), s);
  }

  public void run() {
    openpadJNI.Client_run(swigCPtr, this);
  }

  public IDObject getID() {
    return new IDObject(openpadJNI.Client_getID(swigCPtr, this), false);
  }

  public void setControls(ControlObject ctrls) {
    openpadJNI.Client_setControls(swigCPtr, this, ControlObject.getCPtr(ctrls), ctrls);
  }

  public void disconnect(SWIGTYPE_p_std__string msg) {
    openpadJNI.Client_disconnect(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(msg));
  }

}
