/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.openpad.server;

public class DPadControl extends ControlObject {
  private long swigCPtr;

  protected DPadControl(long cPtr, boolean cMemoryOwn) {
    super(openpadJNI.DPadControl_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DPadControl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        openpadJNI.delete_DPadControl(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DPadControl(float x, float y, float w, int controlid) {
    this(openpadJNI.new_DPadControl(x, y, w, controlid), true);
  }

}
