/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class GameObject extends Serializable {
  private long swigCPtr;

  protected GameObject(long cPtr, boolean cMemoryOwn) {
    super(openpadJNI.GameObject_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GameObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        openpadJNI.delete_GameObject(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public GameObject() {
    this(openpadJNI.new_GameObject(), true);
  }

  public SWIGTYPE_p_Value serializeJSON(SWIGTYPE_p_Document__AllocatorType a) {
    return new SWIGTYPE_p_Value(openpadJNI.GameObject_serializeJSON(swigCPtr, this, SWIGTYPE_p_Document__AllocatorType.getCPtr(a)), false);
  }

  public boolean parseJSON(SWIGTYPE_p_Value v) {
    return openpadJNI.GameObject_parseJSON(swigCPtr, this, SWIGTYPE_p_Value.getCPtr(v));
  }

  public void setName(String value) {
    openpadJNI.GameObject_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return openpadJNI.GameObject_name_get(swigCPtr, this);
  }

  public void setOpenslots(int value) {
    openpadJNI.GameObject_openslots_set(swigCPtr, this, value);
  }

  public int getOpenslots() {
    return openpadJNI.GameObject_openslots_get(swigCPtr, this);
  }

  public void setFilledslots(int value) {
    openpadJNI.GameObject_filledslots_set(swigCPtr, this, value);
  }

  public int getFilledslots() {
    return openpadJNI.GameObject_filledslots_get(swigCPtr, this);
  }

  public void setIcon(String value) {
    openpadJNI.GameObject_icon_set(swigCPtr, this, value);
  }

  public String getIcon() {
    return openpadJNI.GameObject_icon_get(swigCPtr, this);
  }

  public void setDesc(String value) {
    openpadJNI.GameObject_desc_set(swigCPtr, this, value);
  }

  public String getDesc() {
    return openpadJNI.GameObject_desc_get(swigCPtr, this);
  }

}
