/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.openpad.server;

public class openpad implements openpadConstants {
  public static void sendMsg(SWIGTYPE_p_TCPSocket sock, Serializable r) {
    openpadJNI.sendMsg(SWIGTYPE_p_TCPSocket.getCPtr(sock), Serializable.getCPtr(r), r);
  }

  public static String getStringFromJSON(SWIGTYPE_p_Value v) {
    return openpadJNI.getStringFromJSON(SWIGTYPE_p_Value.getCPtr(v));
  }

}
