/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PadUpdateObject {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PadUpdateObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PadUpdateObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        openpadJNI.delete_PadUpdateObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean parseJSON(SWIGTYPE_p_Value v) {
    return openpadJNI.PadUpdateObject_parseJSON(swigCPtr, this, SWIGTYPE_p_Value.getCPtr(v));
  }

  public void setX(int value) {
    openpadJNI.PadUpdateObject_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return openpadJNI.PadUpdateObject_x_get(swigCPtr, this);
  }

  public void setY(int value) {
    openpadJNI.PadUpdateObject_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return openpadJNI.PadUpdateObject_y_get(swigCPtr, this);
  }

  public void setControlid(int value) {
    openpadJNI.PadUpdateObject_controlid_set(swigCPtr, this, value);
  }

  public int getControlid() {
    return openpadJNI.PadUpdateObject_controlid_get(swigCPtr, this);
  }

  public void setAction(int value) {
    openpadJNI.PadUpdateObject_action_set(swigCPtr, this, value);
  }

  public int getAction() {
    return openpadJNI.PadUpdateObject_action_get(swigCPtr, this);
  }

  public PadUpdateObject() {
    this(openpadJNI.new_PadUpdateObject(), true);
  }

}
