/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.openpad.server;

public class Request extends Serializable {
  private long swigCPtr;

  protected Request(long cPtr, boolean cMemoryOwn) {
    super(openpadJNI.Request_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Request obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        openpadJNI.delete_Request(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setOperation(int value) {
    openpadJNI.Request_operation_set(swigCPtr, this, value);
  }

  public int getOperation() {
    return openpadJNI.Request_operation_get(swigCPtr, this);
  }

  public void setTimestamp(int value) {
    openpadJNI.Request_timestamp_set(swigCPtr, this, value);
  }

  public int getTimestamp() {
    return openpadJNI.Request_timestamp_get(swigCPtr, this);
  }

  public void setRoot(SWIGTYPE_p_Document value) {
    openpadJNI.Request_root_set(swigCPtr, this, SWIGTYPE_p_Document.getCPtr(value));
  }

  public SWIGTYPE_p_Document getRoot() {
    long cPtr = openpadJNI.Request_root_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Document(cPtr, false);
  }

  public Request() {
    this(openpadJNI.new_Request__SWIG_0(), true);
  }

  public Request(int op) {
    this(openpadJNI.new_Request__SWIG_1(op), true);
  }

  public boolean parseJSON(String json) {
    return openpadJNI.Request_parseJSON(swigCPtr, this, json);
  }

  public SWIGTYPE_p_Value serializeJSON(SWIGTYPE_p_Document__AllocatorType a) {
    return new SWIGTYPE_p_Value(openpadJNI.Request_serializeJSON(swigCPtr, this, SWIGTYPE_p_Document__AllocatorType.getCPtr(a)), false);
  }

}
