/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.openpad.server;

public class Server {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Server(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Server obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        openpadJNI.delete_Server(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCurrentClientID(int value) {
    openpadJNI.Server_currentClientID_set(swigCPtr, this, value);
  }

  public int getCurrentClientID() {
    return openpadJNI.Server_currentClientID_get(swigCPtr, this);
  }

  public void setClients(SWIGTYPE_p_mapT_int_openpad__Client_R_t value) {
    openpadJNI.Server_clients_set(swigCPtr, this, SWIGTYPE_p_mapT_int_openpad__Client_R_t.getCPtr(value));
  }

  public SWIGTYPE_p_mapT_int_openpad__Client_R_t getClients() {
    long cPtr = openpadJNI.Server_clients_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mapT_int_openpad__Client_R_t(cPtr, false);
  }

  public void setShouldRun(boolean value) {
    openpadJNI.Server_shouldRun_set(swigCPtr, this, value);
  }

  public boolean getShouldRun() {
    return openpadJNI.Server_shouldRun_get(swigCPtr, this);
  }

  public void setHandler(ServerHandler value) {
    openpadJNI.Server_handler_set(swigCPtr, this, ServerHandler.getCPtr(value), value);
  }

  public ServerHandler getHandler() {
    return new ServerHandler(openpadJNI.Server_handler_get(swigCPtr, this), false);
  }

  public Server(ServerHandler handler) {
    this(openpadJNI.new_Server(ServerHandler.getCPtr(handler), handler), true);
  }

  public void start() {
    openpadJNI.Server_start(swigCPtr, this);
  }

  public void refreshClients() {
    openpadJNI.Server_refreshClients(swigCPtr, this);
  }

  public void setControls(ControlObject ctrls) {
    openpadJNI.Server_setControls(swigCPtr, this, ControlObject.getCPtr(ctrls), ctrls);
  }

  public void handleResponse(Response r, Client cli) {
    openpadJNI.Server_handleResponse(swigCPtr, this, Response.getCPtr(r), r, Client.getCPtr(cli), cli);
  }

}
